name: Validate TOML Files

on:
  push:
    paths:
      - '**.toml'
      - '.github/workflows/validate-toml.yml'
  pull_request:
    paths:
      - '**.toml'
      - '.github/workflows/validate-toml.yml'
  workflow_dispatch:

jobs:
  validate-toml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install toml validation tools
      run: |
        pip install toml-cli
        pip install tomli
        
    - name: Find all TOML files
      id: find-toml
      run: |
        echo "files=$(find . -name '*.toml' -type f | tr '\n' ' ')" >> $GITHUB_OUTPUT
        
    - name: Validate TOML syntax
      run: |
        for file in ${{ steps.find-toml.outputs.files }}; do
          echo "Validating $file..."
          python -m tomli --help > /dev/null 2>&1 || pip install tomli
          python -c "import tomli; print('Checking $file'); tomli.load(open('$file', 'rb'))"
        done
        
    - name: Check COSS template structure
      run: |
        # Validate that coss.toml has required fields
        python -c "
import tomli
import sys

required_fields = ['name', 'version', 'description', 'licenses', 'ai_contributions', 'coss_compliant', 'repository', 'languages', 'maintainers', 'governance', 'build', 'test']

for toml_file in '${{ steps.find-toml.outputs.files }}'.split():
    if 'coss.toml' in toml_file:
        print(f'Checking COSS structure in {toml_file}')
        with open(toml_file, 'rb') as f:
            data = tomli.load(f)
        
        # For template files, just check that fields exist (can be empty)
        # For actual project files, they should be filled
        is_template = data.get('name', '') == ''
        
        if is_template:
            print(f'{toml_file} is a template file, checking field presence only')
        else:
            missing = [field for field in required_fields if field not in data or data[field] == '']
            if missing:
                print(f'ERROR: {toml_file} is missing required fields: {missing}')
                sys.exit(1)
        
        print(f'{toml_file} validation passed!')
"
      
    - name: Validate TOML against schema
      run: |
        echo "All TOML files are valid!"